/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timefair.gui;

/**
 *
 * @author Notebook
 */
public class RealizarSolicitud extends javax.swing.JPanel {

    /**
     * Creates new form Solicitudes
     */
    public RealizarSolicitud() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jComboBoxTipoSolicitud = new javax.swing.JComboBox();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Mensaje adicional (opcional)");
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 380, 90));

        jComboBoxTipoSolicitud.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBoxTipoSolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        jFormattedTextField1.setText("Fecha inicio");
        add(jFormattedTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, -1));

        jFormattedTextField2.setText("Fecha Fin");
        add(jFormattedTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, -1, -1));

        jButton1.setText("Solicitar");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBoxTipoSolicitud;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
