/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timefair.gui;

/**
 *
 * @author Notebook
 */
public class TimeRegister extends javax.swing.JPanel {

    /**
     * Creates new form TimeRegister
     */
    public TimeRegister() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxEmpleadosPorHoras = new javax.swing.JComboBox();
        jTextFieldHorasTrabajadas = new javax.swing.JTextField();
        jButtonRegistrar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBoxEmpleadosPorHoras.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBoxEmpleadosPorHoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        jTextFieldHorasTrabajadas.setText("Horas Trabajadas");
        add(jTextFieldHorasTrabajadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 110, -1));

        jButtonRegistrar.setText("Registrar");
        add(jButtonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JComboBox jComboBoxEmpleadosPorHoras;
    private javax.swing.JTextField jTextFieldHorasTrabajadas;
    // End of variables declaration//GEN-END:variables
}
